<?php
/*
 * Implements hook_block_info()
 */
function hero_statement_block_info() {
  $blocks['hero_statement'] = array(
    'info' => t('Hero Statement'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
} // hero_statement_block_info()

/* 
 * Implements hook_block_configure()
 */
function hero_statement_block_configure($delta = '') {
  $form = array();

  if ($delta == 'hero_statement') {
    $text = variable_get('hero_statement_text', array('value' => '', 'format' => 'filtered_html'));
    $form['hero_statement_text'] = array(
      '#type' => 'text_format',
      '#title' => t('Hero Statement'),
      '#description' => t('Enter your Hero Statement here.'),
      '#default_value' => $text['value'],
      '#format' => $text['format'],
      '#required' => TRUE,
    );
    $form['hero_statement_link'] = array(
      '#type' => 'textfield',
      '#title' => t('Learn More Link'),
      '#description' => t('Enter the full URL for your Learn More link. Leave blank to hide the Learn More button.'),
      '#default_value' => variable_get('hero_statement_link', url('about', array('absolute' => TRUE))),
      '#size' => 60,
    );
  } // if hero_statement

  return $form;
} // hero_statement_block_configure()

/*
 * Implements hook_block_save()
 */
function hero_statement_block_save($delta = '', $edit = array()) {
  if ($delta == 'hero_statement') {
    variable_set('hero_statement_text', $edit['hero_statement_text']);
    variable_set('hero_statement_link', $edit['hero_statement_link']);
  } // if hero_statement
} // hero_statement_block_save()

/*
 * Implements hook_block_view()
 */
function hero_statement_block_view($delta = '') {
  $block = array();

  if ($delta == 'hero_statement') {
    $text = variable_get('hero_statement_text', array('value' => '', 'format' => 'filtered_html'));
    $text = '<div class="hero-statement-text">' . check_markup($text['value'], $text['format']) . '</div>';

    $url = variable_get('hero_statement_link');
    if (!empty($url) && !preg_match('/^http/', $url)) $url = 'http://' . $url;
    if (!empty($url)) $url = '<div class="hero-statement-link">' . l(t('Learn More'), $url) . '</div>';


    $block['content'] = $text . $url;

  } // if hero_statement

  return $block;
} // hero_statement_block_view()
