<?php

/*
 * Implements hook_block_info()
 */
function apachesolr_search_block_block_info() {
  $blocks['apachesolr_search_block'] = array(
    'info' => t('Apache Solr Search Block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
} // apachesolr_search_block_block_info()

/*
 * implements hook_block_view()
 */
function apachesolr_search_block_block_view($delta = '') {
  $block = array();

  if ($delta == 'apachesolr_search_block') {
    // get the search page and keys
    $args = arg();
    $keys = (count($args) > 1)? array_pop($args) : '';
    $search_page = apachesolr_search_block_page_load_by_path(implode('/', $args));
    if ($search_page) {
      $block['subject'] = (!empty($search_page->description))? $search_page->description : $search_page->page_title;
      $block['content'] = drupal_get_form('apachesolr_search_custom_page_search_form', $search_page, $keys);      
    }
  } // if apachesolr_search_block

  return $block;
} // apachesolr_search_block_block_view()

/*
 * Implements hook_apaachesolr_search_page_alter()
 */
function apachesolr_search_block_apachesolr_search_page_alter(&$elems) {
  // Hide the search form; we'll show it in a block instead.
  unset($elems['search_form']);
}

function apachesolr_search_block_page_load_by_path($search_path) {
  $pages = &drupal_static(__FUNCTION__, array());

  if (!isset($pages[$search_path])) {
    $page = db_query('SELECT * FROM {apachesolr_search_page} s WHERE s.search_path = :search_path', array(':search_path' => $search_path))->fetchObject();
    if ($page) {
      $page->settings = unserialize($page->settings);
      // Special case page - always uses the default environment.
      if ($page->page_id == 'core_search') {
        $page->env_id = apachesolr_default_environment();
      }
    }
    $pages[$search_path] = $page;
  }
  return $pages[$search_path];
}

